# Generated by Django 4.2.18 on 2025-02-05 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatconversation",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="user",
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="conversation_id",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="swarm.chatconversation",
                    ),
                ),
            ],
        ),
    ]
