# Generated by Django 4.2.18 on 2025-02-05 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0002_remove_chatconversation_conversation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
