# Generated by Django 4.2.18 on 2025-02-06 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0003_alter_chatconversation_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatconversation",
            name="id",
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="conversation_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
