# Generated by Django 4.2.18 on 2025-02-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0004_remove_chatconversation_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["timestamp"]},
        ),
    ]
