# Generated by Django 4.2.18 on 2025-02-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0005_alter_chatmessage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="tool_call_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
