# Generated by Django 4.2.18 on 2025-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0006_chatmessage_tool_call_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversation",
            name="conversation_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
