# Generated by Django 4.2.18 on 2025-02-08 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0007_alter_chatconversation_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="messages",
            field=models.ManyToManyField(
                related_name="conversations", to="swarm.chatmessage"
            ),
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="swarm.chatconversation",
            ),
        ),
    ]
