# Generated by Django 4.2.18 on 2025-02-16 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("swarm", "0009_course_enrollment_teachingunit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="teaching_units",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="learningobjective",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="subtopic",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="teaching_unit",
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="AssessmentItem",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="LearningObjective",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Subtopic",
        ),
        migrations.DeleteModel(
            name="TeachingUnit",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
